#ifndef GROUPS_SCHREIER_SIMS_H
#define GROUPS_SCHREIER_SIMS_H

#include <cstddef>
#include <cstdint>
#include <vector>

#include "group_ops.h"
#include "perm.h"

namespace groups {

struct StabilizerLevel {
  uint32_t base_point = 0u;
  OrbitTraversal orbit;
  std::vector<Permutation> generators;
};

class SchreierSims {
 public:
  explicit SchreierSims(std::size_t degree) : degree_(degree) {}
  SchreierSims(std::size_t degree, std::vector<Permutation> generators);

  void SetGenerators(std::vector<Permutation> generators);
  void AddGenerator(const Permutation& generator);

  void Build();

  bool Contains(const Permutation& element) const;
  uint64_t Order() const;

  std::size_t Degree() const;
  const std::vector<uint32_t>& Base() const;
  const std::vector<StabilizerLevel>& Levels() const;

 private:
  std::size_t degree_;
  std::vector<Permutation> generators_;
  std::vector<uint32_t> base_;
  std::vector<StabilizerLevel> levels_;
};

// Keeps only generators that are not already in the subgroup generated by
// previously kept generators (after deduplication). This gives a compact
// equivalent generating set.
std::vector<Permutation> ReduceGeneratorsByMembership(
    std::vector<Permutation> generators, std::size_t degree);

// Builds generators for the pointwise stabilizer of `fixed_points` inside
// <generators>, using iterative orbit+Schreier reduction.
std::vector<Permutation> BuildPointwiseStabilizerGenerators(
    const std::vector<Permutation>& generators,
    const std::vector<uint32_t>& fixed_points, std::size_t degree);

// Refreshes cached stabilizer generators when `*cached_epoch` is stale.
void RefreshPointwiseStabilizerFromGlobal(
    const std::vector<Permutation>& global_generators,
    const std::vector<uint32_t>& fixed_points, std::size_t degree,
    uint64_t global_epoch, std::vector<Permutation>* cached_generators,
    uint64_t* cached_epoch);

// From a parent stabilizer generator set, builds the child stabilizer after
// additionally fixing `new_fixed_point`.
bool BuildChildPointStabilizerGenerators(
    const std::vector<Permutation>& parent_stabilizer_generators,
    uint32_t new_fixed_point, std::size_t degree,
    std::vector<Permutation>* child_stabilizer_generators);

}  // namespace groups

#endif
